### ISSUE TITLE
Query regarding generating Seurat file using CRE

### ISSUE THREAD

**Issue by raunakkar** [jiawei-zhong/Mao_et_al_DR#1]
Hi,
Wonderful analysis in the paper. It got me intrigued as I want to do something similar with my dataset. I am very naive in this field and have just started looking into CREs. Could you please help me in understanding how you went from the SCAFE output to merging it with the Seurat RNA data?
I would be very grateful if you can kindly guide me here.

Thank you in advance.

**Comment by jiawei-zhong** [comment]
Hi,

To process your samples, you should start by using "scafe.workflow.sc.solo" for each individual sample. After this, employ "scafe.workflow.cm.aggregate" and "scafe.tool.sc.count" to ensure that every sample has consistent features. This step is crucial for accurate analysis and comparison across samples. For more information, please refer to https://github.com/chung-lab/SCAFE/issues/18

Best,
Jiawei
