### ISSUE TITLE
U09.R CreateChromatinAssay()

### ISSUE THREAD

**Issue by marsa04** [jiawei-zhong/Mao_et_al_DR#2]
Hi, 
you performed wonderful analysis in you article. Could you please explain how you got the "snapATAC/output_sorted_new.bed.gz" file that you used in the CreateChromatinAssay() function? 
https://github.com/jiawei-zhong/Mao_et_al_DR/blob/main/U09.R line 60

I spent a lot of time to understand what can be used as a fragments file and I will be very grateful if you help me with this.
Thank you in advance.

**Comment by jiawei-zhong** [comment]
Hey,

the fragments file looks like this:
```
chr1    3293441 3293742 CTRL1_CAGAATCTCCGCAAGC.1        1
chr1    3293441 3293742 DM1_AACTTTCTCCTACAGA.1  1
chr1    3293441 3293742 DM1_CTCTGGTAGGTGCAAC.1  1
chr1    3293441 3293742 DM1_GGGAATGCAAACCTAC.1  1
chr1    3293441 3293742 DM1_TATCTCAGTTCGGGCT.1  1
chr1    3293441 3293742 DM1_TGGTTCCTCGAGCCCA.1  1
chr1    3293441 3293742 DM2_CCTCTGAGTTACGGAG.1  1
chr1    3293441 3293742 DM2_TCACGAATCGCCTGAG.1  1
chr1    3293441 3293742 DM3_GGCGACTAGACTAGAT.1  1
chr1    3293441 3293742 DM3_TACTTGTTCTGAGGGA.1  1
```

Best,
Jiawei
